************* Module django.contrib.admin
/usr/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py:6: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
    ModelAdmin, StackedInline, TabularInline)
    ^                                     |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py:8: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
    FieldListFilter, BooleanFieldListFilter, RelatedFieldListFilter,
    ^                                     |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py:9: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
    ChoicesFieldListFilter, DateFieldListFilter, AllValuesFieldListFilter,
    ^                                     |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py:10: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
    RelatedOnlyFieldListFilter)
    ^                                     |
************* Module django.contrib.admin.actions
/usr/local/lib/python2.7/site-packages/django/contrib/admin/actions.py:15: [R0914(too-many-locals), delete_selected] Too many local variables (16/15)
************* Module django.contrib.admin.tests
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:45: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_until] Unable to import 'selenium.webdriver.support.wait'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:66: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_for] Unable to import 'selenium.webdriver.common.by'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:67: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_for] Unable to import 'selenium.webdriver.support'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:77: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_for_text] Unable to import 'selenium.webdriver.common.by'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:78: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_for_text] Unable to import 'selenium.webdriver.support'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:89: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_for_value] Unable to import 'selenium.webdriver.common.by'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:90: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_for_value] Unable to import 'selenium.webdriver.support'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:101: [E0401(import-error), AdminSeleniumWebDriverTestCase.wait_page_loaded] Unable to import 'selenium.common.exceptions'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/tests.py:139: [E0401(import-error), AdminSeleniumWebDriverTestCase.get_select_option] Unable to import 'selenium.common.exceptions'
************* Module django.contrib.admin.checks
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:1: [C0302(too-many-lines), ] Too many lines in module (972/500)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:118: [R0911(too-many-return-statements), BaseModelAdminChecks._check_fieldsets_item] Too many return statements (7/6)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:581: [R0911(too-many-return-statements), ModelAdminChecks._check_list_display_item] Too many return statements (7/6)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:677: [R0911(too-many-return-statements), ModelAdminChecks._check_list_filter_item] Too many return statements (7/6)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:940: [W0622(redefined-builtin), must_be] Redefining built-in 'type'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:940: [W0622(redefined-builtin), must_be] Redefining built-in 'id'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:951: [W0622(redefined-builtin), must_inherit_from] Redefining built-in 'id'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/checks.py:962: [W0622(redefined-builtin), refer_to_missing_field] Redefining built-in 'id'
************* Module django.contrib.admin.filters
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:161: [C0330(bad-continuation), ] Wrong continued indentation (add 21 spaces).
                model, model_admin, field_path=field_path)
                ^                    |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:204: [C0330(bad-continuation), ] Wrong continued indentation (add 32 spaces).
                [self.lookup_kwarg, self.lookup_kwarg_isnull]),
                ^                               |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:238: [C0330(bad-continuation), ] Wrong continued indentation (add 41 spaces).
            request, params, model, model_admin, field_path)
            ^                                        |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:265: [C0330(bad-continuation), ] Wrong continued indentation (add 42 spaces).
    (models.BooleanField, models.NullBooleanField)), BooleanFieldListFilter)
    ^                                         |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:395: [C0330(bad-continuation), ] Wrong continued indentation (add 9 spaces).
                and self.lookup_val_isnull is None),
                ^        |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:397: [C0330(bad-continuation), ] Wrong continued indentation (add 32 spaces).
                [self.lookup_kwarg, self.lookup_kwarg_isnull]),
                ^                               |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:119: [W0223(abstract-method), FieldListFilter] Method 'choices' is abstract in class 'ListFilter' but is not overridden
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:119: [W0223(abstract-method), FieldListFilter] Method 'expected_parameters' is abstract in class 'ListFilter' but is not overridden
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:215: [R0916(too-many-boolean-expressions), RelatedFieldListFilter.choices] Too many boolean expressions in if statement (6/5)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/filters.py:368: [W0612(unused-variable), AllValuesFieldListFilter.__init__] Unused variable 'reverse_path'
************* Module django.contrib.admin.utils
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:274: [C0330(bad-continuation), ] Wrong continued indentation (remove 2 spaces).
                hasattr(model_admin, name) and
              | ^
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:275: [C0330(bad-continuation), ] Wrong continued indentation (remove 2 spaces).
                not name == '__str__' and
              | ^
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:276: [C0330(bad-continuation), ] Wrong continued indentation (remove 2 spaces).
                not name == '__unicode__'):
              | ^
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:1: [C0302(too-many-lines), ] Too many lines in module (508/500)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:58: [C0200(consider-using-enumerate), quote] Consider using enumerate instead of iterating with range and len
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:71: [W0622(redefined-builtin), unquote] Redefining built-in 'list'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:101: [W0612(unused-variable), flatten_fieldsets] Unused variable 'name'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:308: [R0912(too-many-branches), label_for_field] Too many branches (18/12)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/utils.py:375: [R0911(too-many-return-statements), display_for_field] Too many return statements (9/6)
************* Module django.contrib.admin.helpers
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:30: [C0330(bad-continuation), ] Wrong continued indentation (add 31 spaces).
        widget=forms.HiddenInput({'class': 'select-across'}))
        ^                              |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:66: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
      description=None, model_admin=None):
      ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:108: [C0330(bad-continuation), ] Wrong continued indentation (add 21 spaces).
                    model_admin=self.model_admin)
                    ^                    |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:115: [C0330(bad-continuation), ] Wrong continued indentation (add 10 spaces).
            for f in self.fields if f not in self.readonly_fields).strip('\n')
            ^         |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:219: [C0330(bad-continuation), ] Wrong continued indentation (add 5 spaces).
            readonly_fields=None, model_admin=None):
            ^    |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:235: [C0330(bad-continuation), ] Wrong continued indentation (add 18 spaces).
                self.prepopulated_fields, original, self.readonly_fields,
                ^                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:236: [C0330(bad-continuation), ] Wrong continued indentation (add 18 spaces).
                model_admin=self.opts, view_on_site_url=view_on_site_url)
                ^                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:239: [C0330(bad-continuation), ] Wrong continued indentation (add 18 spaces).
                self.prepopulated_fields, None, self.readonly_fields,
                ^                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:240: [C0330(bad-continuation), ] Wrong continued indentation (add 18 spaces).
                model_admin=self.opts)
                ^                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:242: [C0330(bad-continuation), ] Wrong continued indentation (add 18 spaces).
            self.fieldsets, self.prepopulated_fields, None,
            ^                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:243: [C0330(bad-continuation), ] Wrong continued indentation (add 18 spaces).
            self.readonly_fields, model_admin=self.opts)
            ^                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:275: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
      readonly_fields=None, model_admin=None, view_on_site_url=None):
      ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:282: [C0330(bad-continuation), ] Wrong continued indentation (add 34 spaces).
            readonly_fields, model_admin)
            ^                                 |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:302: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
                self.readonly_fields, model_admin=self.model_admin, **options)
                ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:345: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                model_admin=self.model_admin)
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:207: [R0204(redefined-variable-type), AdminReadonlyField.contents] Redefinition of result_repr type from django.utils.functional.lazy.__proxy__ to unicode
/usr/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py:247: [W0612(unused-variable), InlineAdminFormSet.fields] Unused variable 'i'
************* Module django.contrib.admin.sites
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:87: [C0330(bad-continuation), ] Wrong continued indentation (add 21 spaces).
                      'cannot be registered with admin.' % model.__name__)
                      ^                    |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:386: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            title=_('Log in'),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:387: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            app_path=request.get_full_path(),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:388: [C0330(bad-continuation), ] Wrong continued indentation (add 14 spaces).
        )
        ^             |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:518: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            title=_('%(app)s administration') % {'app': app_name},
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:519: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            app_list=[app_dict],
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:520: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            app_label=app_label,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:521: [C0330(bad-continuation), ] Wrong continued indentation (add 14 spaces).
        )
        ^             |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:1: [C0302(too-many-lines), ] Too many lines in module (533/500)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:181: [W0703(broad-except), AdminSite.check_dependencies] Catching too general exception Exception
/usr/local/lib/python2.7/site-packages/django/contrib/admin/sites.py:501: [W0106(expression-not-assigned), AdminSite.app_index] Expression "(app_dict['models'].append(model_dict), )" is assigned to nothing
************* Module django.contrib.admin.models
/usr/local/lib/python2.7/site-packages/django/contrib/admin/models.py:72: [E1101(no-member), LogEntry.get_edited_object] Instance of 'ForeignKey' has no 'get_object_for_this_type' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/models.py:79: [E1101(no-member), LogEntry.get_admin_url] Instance of 'ForeignKey' has no 'app_label' member
************* Module django.contrib.admin.util
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0401(wildcard-import), ] Wildcard import django.contrib.admin.utils
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [C0413(wrong-import-position), ] Import "from django.contrib.admin.utils import *" should be placed at the top of the module
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import unquote from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import get_model_from_relation from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import reverse_field_path from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import model_format_dict from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import LOOKUP_SEP from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import datetime from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import smart_text from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import flatten from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import timezone from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import NoReverseMatch from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import force_text from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import flatten_fieldsets from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import ungettext from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import get_limit_choices_to_from_path from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import six from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import get_deleted_objects from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import get_permission_codename from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import display_for_field from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import label_for_field from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import NotRelationField from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import model_ngettext from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import defaultdict from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import remove_trailing_data_field from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import models from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import quote from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import prepare_lookup_value from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import lookup_field from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import NestedObjects from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import format_html from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import reverse from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import pretty_name from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import display_for_value from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import decimal from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import get_fields_from_path from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import help_text_for_field from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import lookup_needs_distinct from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import formats from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import force_str from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import FieldDoesNotExist from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import Collector from wildcard import
/usr/local/lib/python2.7/site-packages/django/contrib/admin/util.py:9: [W0614(unused-wildcard-import), ] Unused import capfirst from wildcard import
************* Module django.contrib.admin.validation
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:52: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        "can't include the ManyToManyField field '%s' because "
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:64: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "be either a ForeignKey or ManyToManyField."
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:65: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            % (cls.__name__, idx, field))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:87: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "have exactly two elements." % (cls.__name__, idx))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:91: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "%s.fieldsets[%d][1] field options dict."
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:92: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            % (cls.__name__, idx))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:109: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                    "BaseModelForm." % cls.__name__)
                    ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:119: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        "a ManyToManyField." % (cls.__name__, idx))
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:129: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        "a ManyToManyField." % (cls.__name__, idx))
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:140: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "is neither an instance of ForeignKey nor does "
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:144: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "is neither admin.HORIZONTAL nor admin.VERTICAL."
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:145: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            % (cls.__name__, field))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:155: [C0330(bad-continuation), ] Wrong continued indentation (add 10 spaces).
                        models.ManyToManyField)):
                        ^         |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:157: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "is either a DateTimeField, ForeignKey or "
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:159: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            % (cls.__name__, field))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:177: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "ordering marker '?', but contains other fields as "
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:179: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            % cls.__name__)
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:225: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "from BaseModelAdmin." % (cls.__name__, idx))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:228: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "of '%s.inlines[%d]'." % (cls.__name__, idx))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:231: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "inherit from models.Model." % (cls.__name__, idx))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:241: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                        "'%s' - this is the foreign key to the parent model "
                        ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:279: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            "refers to '%s' which is not defined in 'list_display'."
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:280: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            % (cls.__name__, idx, field))
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:297: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                " which is not a descendant of ListFilter."
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:298: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                % (cls.__name__, idx, item.__name__))
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:302: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                " which is of type FieldListFilter but is not"
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:304: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                % (cls.__name__, idx, item.__name__))
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:311: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                                " is '%s' which is not of type FieldListFilter."
                                ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:312: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                                % (cls.__name__, idx, list_filter_class.__name__))
                                ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:321: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                " which does not refer to a Field."
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:322: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                % (cls.__name__, idx, field))
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:354: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        "field, '%s', not defined on %s.%s."
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:355: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        % (cls.__name__, idx, field_name, model._meta.app_label, model.__name__))
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:358: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        "'%s' which is not defined in 'list_display'."
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:359: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        % (cls.__name__, idx, field_name))
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:363: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                            " and '%s.list_display_links'"
                            ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:364: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                            % (field_name, cls.__name__, cls.__name__))
                            ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:367: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                            " the first field in list_display, '%s', which can't be"
                            ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:369: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                            % (cls.__name__, idx, cls.list_display[0]))
                            ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:372: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        "field, '%s', which isn't editable through the admin."
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:373: [C0330(bad-continuation), ] Wrong continued indentation (add 23 spaces).
                        % (cls.__name__, idx, field_name))
                        ^                      |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:386: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                        "neither an instance of DateField nor DateTimeField."
                        ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:387: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                        % cls.__name__)
                        ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:397: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                        "models.ForeignKey." % cls.__name__)
                        ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:411: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                    "BaseModelFormSet." % cls.__name__)
                    ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:417: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                % (cls.__name__, attr, type_.__name__))
                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:435: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                % (cls.__name__, label, field, model._meta.app_label, model.__name__))
                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:12: [W0105(pointless-string-statement), ] String statement has no effect
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:35: [C0123(unidiomatic-typecheck), BaseValidator.check_field_spec] Using type() instead of isinstance() for a typecheck.
/usr/local/lib/python2.7/site-packages/django/contrib/admin/validation.py:246: [R0101(too-many-nested-blocks), ModelAdminValidator.validate_list_display] Too many nested blocks (6/5)
************* Module django.contrib.admin.widgets
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:50: [W0511(fixme), ] TODO: "id_" is hard-coded here. This should instead use the correct
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:175: [W0511(fixme), ] TODO: "lookup_id_" is hard-coded here. This should instead use
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:253: [W0511(fixme), ] XXX: The UX does not support multiple selected values.
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:256: [W0511(fixme), ] XXX: The deletion UX can be confusing when dealing with cascading deletion.
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:53: [C0330(bad-continuation), ] Wrong continued indentation (add 10 spaces).
            % (name, self.verbose_name.replace('"', '\\"'), int(self.is_stacked), static('admin/')))
            ^         |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:114: [C0330(bad-continuation), ] Wrong continued indentation (add 1 space).
                            % forms.ClearableFileInput.template_with_initial)
                            ^|
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:178: [C0330(bad-continuation), ] Wrong continued indentation (add 9 spaces).
                (related_url, url, name, _('Lookup')))
                ^        |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:63: [W0622(redefined-builtin), AdminDateWidget.__init__] Redefining built-in 'format'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:76: [W0622(redefined-builtin), AdminTimeWidget.__init__] Redefining built-in 'format'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:91: [W0233(non-parent-init-called), AdminSplitDateTime.__init__] __init__ method from a non direct base class 'MultiWidget' is called
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:87: [W0231(super-init-not-called), AdminSplitDateTime.__init__] __init__ method from base class 'SplitDateTimeWidget' is not called
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:234: [R0902(too-many-instance-attributes), RelatedFieldWidgetWrapper] Too many instance attributes (9/7)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/widgets.py:241: [W0231(super-init-not-called), RelatedFieldWidgetWrapper.__init__] __init__ method from base class 'Widget' is not called
************* Module django.contrib.admin.options
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:380: [W0511(fixme), ] TODO: this should be handled by some parameter to the ChangeList.
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1118: [W0511(fixme), ] FIXME - this should check if form or formsets have a FileField,
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:253: [C0330(bad-continuation), ] Wrong continued indentation (add 25 spaces).
                                    self.admin_site, using=db)
                                    ^                        |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:279: [C0330(bad-continuation), ] Wrong continued indentation (add 25 spaces).
                                    self.admin_site, using=db)
                                    ^                        |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:281: [C0325(superfluous-parens), ] Unnecessary parens after 'in' keyword
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:753: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
            self.get_changelist_form(request), extra=0,
            ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:754: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
            fields=self.list_editable, **defaults)
            ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1064: [C0330(bad-continuation), ] Wrong continued indentation (add 9 spaces).
                        'Possible values are: %s' % (level, levels_repr))
                        ^        |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1067: [C0330(bad-continuation), ] Wrong continued indentation (add 13 spaces).
                fail_silently=fail_silently)
                ^            |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1363: [C0330(bad-continuation), ] Wrong continued indentation (add 14 spaces).
            _('The %(name)s "%(obj)s" was deleted successfully.') % {
            ^             |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1392: [C0330(bad-continuation), ] Wrong continued indentation (add 20 spaces).
            self.delete_confirmation_template or [
            ^                   |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1406: [C0330(bad-continuation), ] Wrong continued indentation (add 46 spaces).
                fieldsets, prepopulated, readonly, model_admin=self)
                ^                                             |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1456: [C0330(bad-continuation), ] Wrong continued indentation (add 43 spaces).
                    current_app=self.admin_site.name))
                    ^                                          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1500: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            title=(_('Add %s') if add else _('Change %s')) % force_text(opts.verbose_name),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1501: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            adminform=adminForm,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1502: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            object_id=object_id,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1503: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            original=obj,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1504: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            is_popup=(IS_POPUP_VAR in request.POST or
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1506: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            to_field=to_field,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1507: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            media=media,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1508: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            inline_admin_formsets=inline_formsets,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1509: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            errors=helpers.AdminErrorList(form, formsets),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1510: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            preserved_filters=self.get_preserved_filters(request),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1511: [C0330(bad-continuation), ] Wrong continued indentation (add 14 spaces).
        )
        ^             |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1548: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                list_display_links, list_filter, self.date_hierarchy,
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1549: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                search_fields, self.list_select_related, self.list_per_page,
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1550: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                self.list_max_show_all, self.list_editable, self)
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1652: [C0330(bad-continuation), ] Wrong continued indentation (add 27 spaces).
            'All %(total_count)s selected', cl.result_count)
            ^                          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1773: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            title=_('Change history: %s') % force_text(obj),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1774: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            action_list=action_list,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1775: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            module_name=capfirst(force_text(opts.verbose_name_plural)),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1776: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            object=obj,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1777: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            opts=opts,
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1778: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
            preserved_filters=self.get_preserved_filters(request),
            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1779: [C0330(bad-continuation), ] Wrong continued indentation (add 14 spaces).
        )
        ^             |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1: [C0302(too-many-lines), ] Too many lines in module (2000/500)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:5: [W0622(redefined-builtin), ] Redefining built-in 'reduce'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:129: [E1102(not-callable), BaseModelAdmin.validate] cls.validator_class is not callable
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:142: [E1102(not-callable), BaseModelAdmin.check] cls.validator_class is not callable
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:191: [E1101(no-member), BaseModelAdmin.formfield_for_dbfield] Instance of 'BaseModelAdmin' has no 'admin_site' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:200: [E1101(no-member), BaseModelAdmin.formfield_for_dbfield] Instance of 'BaseModelAdmin' has no 'admin_site' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:239: [E1101(no-member), BaseModelAdmin.get_field_queryset] Instance of 'BaseModelAdmin' has no 'admin_site' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:253: [E1101(no-member), BaseModelAdmin.formfield_for_foreignkey] Instance of 'BaseModelAdmin' has no 'admin_site' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:279: [E1101(no-member), BaseModelAdmin.formfield_for_manytomany] Instance of 'BaseModelAdmin' has no 'admin_site' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:304: [E1102(not-callable), BaseModelAdmin.get_view_on_site_url] self.view_on_site is not callable
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:379: [E1101(no-member), BaseModelAdmin.get_queryset] Instance of 'BaseModelAdmin' has no 'model' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:389: [E1101(no-member), BaseModelAdmin.lookup_allowed] Instance of 'BaseModelAdmin' has no 'model' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:441: [E1101(no-member), BaseModelAdmin.lookup_allowed] Instance of 'BaseModelAdmin' has no 'date_hierarchy' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:442: [E1101(no-member), BaseModelAdmin.lookup_allowed] Instance of 'BaseModelAdmin' has no 'list_filter' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:386: [R0912(too-many-branches), BaseModelAdmin.lookup_allowed] Too many branches (19/12)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:456: [E1101(no-member), BaseModelAdmin.to_field_allowed] Instance of 'BaseModelAdmin' has no 'model' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:477: [E1101(no-member), BaseModelAdmin.to_field_allowed] Instance of 'BaseModelAdmin' has no 'admin_site' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:501: [E1101(no-member), BaseModelAdmin.has_add_permission] Instance of 'BaseModelAdmin' has no 'opts' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:516: [E1101(no-member), BaseModelAdmin.has_change_permission] Instance of 'BaseModelAdmin' has no 'opts' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:531: [E1101(no-member), BaseModelAdmin.has_delete_permission] Instance of 'BaseModelAdmin' has no 'opts' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:546: [E1101(no-member), BaseModelAdmin.has_module_permission] Instance of 'BaseModelAdmin' has no 'opts' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:790: [W0125(using-constant-test), ModelAdmin.get_formsets_with_inlines] Using a conditional statement with a constant value
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:801: [W0622(redefined-builtin), ModelAdmin.log_addition] Redefining built-in 'object'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:816: [W0622(redefined-builtin), ModelAdmin.log_change] Redefining built-in 'object'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:832: [W0622(redefined-builtin), ModelAdmin.log_deletion] Redefining built-in 'object'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:875: [E1101(no-member), ModelAdmin.get_actions] Class 'ModelAdmin' has no 'mro' member
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:886: [R0204(redefined-variable-type), ModelAdmin.get_actions] Redefinition of actions type from list to collections.OrderedDict
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:893: [W0102(dangerous-default-value), ModelAdmin.get_action_choices] Dangerous default value BLANK_CHOICE_DASH (__builtin__.list) as argument
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:899: [W0612(unused-variable), ModelAdmin.get_action_choices] Unused variable 'func'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1041: [R0204(redefined-variable-type), ModelAdmin.construct_change_message] Redefinition of change_message type from list to str
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1428: [R0914(too-many-locals), ModelAdmin.changeform_view] Too many local variables (23/15)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1428: [R0912(too-many-branches), ModelAdmin.changeform_view] Too many branches (16/12)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1524: [R0914(too-many-locals), ModelAdmin.changelist_view] Too many local variables (28/15)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1543: [R0204(redefined-variable-type), ModelAdmin.changelist_view] Redefinition of list_display type from tuple to list
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1524: [R0912(too-many-branches), ModelAdmin.changelist_view] Too many branches (25/12)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1524: [R0915(too-many-statements), ModelAdmin.changelist_view] Too many statements (72/50)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/options.py:1684: [R0914(too-many-locals), ModelAdmin.delete_view] Too many local variables (19/15)
************* Module django.contrib.admin.views.main
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:42: [C0330(bad-continuation), ] Wrong continued indentation (add 5 spaces).
            list_filter, date_hierarchy, search_fields, list_select_related,
            ^    |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:43: [C0330(bad-continuation), ] Wrong continued indentation (add 5 spaces).
            list_per_page, list_max_show_all, list_editable, model_admin):
            ^    |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:118: [C0330(bad-continuation), ] Wrong continued indentation (add 15 spaces).
                        self.model, self.model_admin)
                        ^              |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:133: [C0330(bad-continuation), ] Wrong continued indentation (add 27 spaces).
                        self.model, self.model_admin, field_path=field_path)
                        ^                          |
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:40: [R0902(too-many-instance-attributes), ChangeList] Too many instance attributes (35/7)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:41: [R0913(too-many-arguments), ChangeList.__init__] Too many arguments (13/10)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:261: [W0612(unused-variable), ChangeList.get_ordering] Unused variable 'none'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/views/main.py:313: [W0612(unused-variable), ChangeList.get_ordering_field_columns] Unused variable 'none'
************* Module django.contrib.admin.templatetags.admin_modify
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_modify.py:61: [W0612(unused-variable), cell_count] Unused variable 'field'
************* Module django.contrib.admin.templatetags.admin_urls
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_urls.py:5: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_urls.py:5: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.parse'
************* Module django.contrib.admin.templatetags.admin_list
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:131: [W0622(redefined-builtin), result_headers] Redefining built-in 'sorted'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:93: [R0914(too-many-locals), result_headers] Too many local variables (19/15)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:182: [R0914(too-many-locals), items_for_result] Too many local variables (21/15)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:182: [R0912(too-many-branches), items_for_result] Too many branches (23/12)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:182: [R0915(too-many-statements), items_for_result] Too many statements (61/50)
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:301: [W0612(unused-variable), result_hidden_fields] Unused variable 'res'
/usr/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py:324: [R0914(too-many-locals), date_hierarchy] Too many local variables (19/15)
************* Module django.contrib.auth
/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py:86: [C0330(bad-continuation), ] Wrong continued indentation (add 15 spaces).
            credentials=_clean_credentials(credentials))
            ^              |
************* Module django.contrib.auth.decorators
/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py:8: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py:8: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.parse'
************* Module django.contrib.auth.forms
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:42: [C0330(bad-continuation), ] Wrong continued indentation (remove 1 space).
                                           )
                                          |^
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:72: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
        widget=forms.PasswordInput)
        ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:74: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
        widget=forms.PasswordInput,
        ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:75: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
        help_text=_("Enter the same password as above, for verification."))
        ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:101: [C0330(bad-continuation), ] Wrong continued indentation (add 33 spaces).
        help_text=_("Raw passwords are not stored, so there is no way to see "
        ^                                |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:25: [W0222(signature-differs), ReadOnlyPasswordHashWidget.render] Signature differs from overridden 'render' method
/usr/local/lib/python2.7/site-packages/django/contrib/auth/forms.py:41: [E1101(no-member), ReadOnlyPasswordHashWidget.render] Instance of 'unicode' has no 'safe_summary' member
************* Module django.contrib.auth.admin
/usr/local/lib/python2.7/site-packages/django/contrib/auth/admin.py:171: [C0330(bad-continuation), ] Wrong continued indentation (add 20 spaces).
            self.change_user_password_template or
            ^                   |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/admin.py:172: [C0330(bad-continuation), ] Wrong continued indentation (add 20 spaces).
            'admin/auth/user/change_password.html',
            ^                   |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/admin.py:173: [C0330(bad-continuation), ] Wrong continued indentation (add 20 spaces).
            context)
            ^                   |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/admin.py:124: [W0622(redefined-builtin), UserAdmin.user_change_password] Redefining built-in 'id'
************* Module django.contrib.auth.models
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:117: [C0330(bad-continuation), ] Wrong continued indentation (add 33 spaces).
        verbose_name=_('permissions'), blank=True)
        ^                                |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:309: [C0330(bad-continuation), ] Wrong continued indentation (add 31 spaces).
        help_text=_('Designates that this user has all permissions without '
        ^                              |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:312: [C0330(bad-continuation), ] Wrong continued indentation (add 28 spaces).
        blank=True, help_text=_('The groups this user belongs to. A user will '
        ^                           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:315: [C0330(bad-continuation), ] Wrong continued indentation (add 28 spaces).
        related_name="user_set", related_query_name="user")
        ^                           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:317: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
        verbose_name=_('user permissions'), blank=True,
        ^                                     |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:318: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
        help_text=_('Specific permissions for this user.'),
        ^                                     |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:319: [C0330(bad-continuation), ] Wrong continued indentation (add 38 spaces).
        related_name="user_set", related_query_name="user")
        ^                                     |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:386: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
        help_text=_('Required. 30 characters or fewer. Letters, digits and '
        ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:388: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
        validators=[
        ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:394: [C0330(bad-continuation), ] Wrong continued indentation (add 24 spaces).
        error_messages={
        ^                       |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:401: [C0330(bad-continuation), ] Wrong continued indentation (add 27 spaces).
        help_text=_('Designates whether the user can log into this admin '
        ^                          |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:404: [C0330(bad-continuation), ] Wrong continued indentation (add 28 spaces).
        help_text=_('Designates whether this user should be treated as '
        ^                           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:1: [C0302(too-many-lines), ] Too many lines in module (518/500)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:78: [E1101(no-member), Permission.__str__] Instance of 'ForeignKey' has no 'app_label' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:83: [E1101(no-member), Permission.natural_key] Instance of 'ForeignKey' has no 'natural_key' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py:208: [E1101(no-member), AbstractBaseUser.get_username] Instance of 'AbstractBaseUser' has no 'USERNAME_FIELD' member
************* Module django.contrib.auth.backends
/usr/local/lib/python2.7/site-packages/django/contrib/auth/backends.py:113: [W0221(arguments-differ), RemoteUserBackend.authenticate] Arguments number differs from overridden 'authenticate' method
************* Module django.contrib.auth.hashers
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:1: [C0302(too-many-lines), ] Too many lines in module (550/500)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:50: [E1101(no-member), check_password] Instance of 'unicode' has no 'algorithm' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:50: [E1101(no-member), check_password] Instance of 'unicode' has no 'algorithm' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:51: [E1101(no-member), check_password] Instance of 'unicode' has no 'must_update' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:52: [E1101(no-member), check_password] Instance of 'unicode' has no 'verify' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:59: [E1101(no-member), check_password] Instance of 'unicode' has no 'harden_runtime' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:82: [E1101(no-member), make_password] Instance of 'unicode' has no 'salt' member
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:157: [W0622(redefined-builtin), mask_hash] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:182: [W0612(unused-variable), BasePasswordHasher._load_library] Unused variable 'name'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:258: [W0622(redefined-builtin), PBKDF2PasswordHasher.encode] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:253: [W0221(arguments-differ), PBKDF2PasswordHasher.encode] Arguments number differs from overridden 'encode' method
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:263: [W0622(redefined-builtin), PBKDF2PasswordHasher.verify] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:263: [W0612(unused-variable), PBKDF2PasswordHasher.verify] Unused variable 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:269: [W0622(redefined-builtin), PBKDF2PasswordHasher.safe_summary] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:279: [W0622(redefined-builtin), PBKDF2PasswordHasher.must_update] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:279: [W0612(unused-variable), PBKDF2PasswordHasher.must_update] Unused variable 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:279: [W0612(unused-variable), PBKDF2PasswordHasher.must_update] Unused variable 'algorithm'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:279: [W0612(unused-variable), PBKDF2PasswordHasher.must_update] Unused variable 'salt'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:283: [W0622(redefined-builtin), PBKDF2PasswordHasher.harden_runtime] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:283: [W0612(unused-variable), PBKDF2PasswordHasher.harden_runtime] Unused variable 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:283: [W0612(unused-variable), PBKDF2PasswordHasher.harden_runtime] Unused variable 'algorithm'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:342: [W0612(unused-variable), BCryptSHA256PasswordHasher.safe_summary] Unused variable 'algostr'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:342: [W0612(unused-variable), BCryptSHA256PasswordHasher.safe_summary] Unused variable 'empty'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:391: [W0622(redefined-builtin), SHA1PasswordHasher.encode] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:395: [W0622(redefined-builtin), SHA1PasswordHasher.verify] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:395: [W0612(unused-variable), SHA1PasswordHasher.verify] Unused variable 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:401: [W0622(redefined-builtin), SHA1PasswordHasher.safe_summary] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:422: [W0622(redefined-builtin), MD5PasswordHasher.encode] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:426: [W0622(redefined-builtin), MD5PasswordHasher.verify] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:426: [W0612(unused-variable), MD5PasswordHasher.verify] Unused variable 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:432: [W0622(redefined-builtin), MD5PasswordHasher.safe_summary] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:460: [W0622(redefined-builtin), UnsaltedSHA1PasswordHasher.encode] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:469: [W0622(redefined-builtin), UnsaltedSHA1PasswordHasher.safe_summary] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py:536: [W0612(unused-variable), CryptPasswordHasher.verify] Unused variable 'salt'
************* Module django.contrib.auth.apps
/usr/local/lib/python2.7/site-packages/django/contrib/auth/apps.py:16: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
            dispatch_uid="django.contrib.auth.management.create_permissions")
            ^                |
************* Module django.contrib.auth.views
/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py:22: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py:22: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.parse'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py:123: [W0622(redefined-builtin), redirect_to_login] Redefining built-in 'next'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py:147: [R0913(too-many-arguments), password_reset] Too many arguments (12/10)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/views.py:217: [R0914(too-many-locals), password_reset_confirm] Too many local variables (16/15)
************* Module django.contrib.auth.tokens
/usr/local/lib/python2.7/site-packages/django/contrib/auth/tokens.py:63: [C0330(bad-continuation), ] Wrong continued indentation (add 1 space).
                six.text_type(login_timestamp) + six.text_type(timestamp))
                ^|
/usr/local/lib/python2.7/site-packages/django/contrib/auth/tokens.py:27: [W0622(redefined-builtin), PasswordResetTokenGenerator.check_token] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/tokens.py:27: [W0612(unused-variable), PasswordResetTokenGenerator.check_token] Unused variable 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/tokens.py:64: [W0622(redefined-builtin), PasswordResetTokenGenerator._make_token_with_timestamp] Redefining built-in 'hash'
************* Module django.contrib.auth.management.__init__
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py:36: [C0330(bad-continuation), ] Wrong continued indentation (add 10 spaces).
            'Can %s %s' % (action, opts.verbose_name_raw)))
            ^         |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py:117: [C0325(superfluous-parens), ] Unnecessary parens after 'print' keyword
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py:163: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                .encode('ascii', 'ignore').decode('ascii')
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py:164: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                .replace(' ', '').lower())
                ^           |
************* Module django.contrib.auth.management
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py:60: [R0914(too-many-locals), create_permissions] Too many local variables (19/15)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/__init__.py:177: [E1101(no-member), get_default_username] Class 'User' has no '_default_manager' member
************* Module django.contrib.auth.management.commands.changepassword
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/changepassword.py:24: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help='Username to change password for; by default, it\'s the current username.')
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/changepassword.py:26: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            default=DEFAULT_DB_ALIAS,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/changepassword.py:27: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help='Specifies the database to use. Default is "default".')
            ^               |
************* Module django.contrib.auth.management.commands.createsuperuser
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:33: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            dest=self.UserModel.USERNAME_FIELD, default=None,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:34: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help='Specifies the login for the superuser.')
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:36: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help=('Tells Django to NOT prompt the user for input of any kind. '
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:42: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                default=DEFAULT_DB_ALIAS,
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:43: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                help='Specifies the database to use. Default is "default".')
                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:46: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
                help='Specifies the %s for the superuser.' % field)
                ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:65: [C0330(bad-continuation), ] Wrong continued indentation (add 11 spaces).
                            self.UserModel.USERNAME_FIELD)
                            ^          |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:100: [C0330(bad-continuation), ] Wrong continued indentation (add 21 spaces).
                    )
                    ^                    |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:110: [C0330(bad-continuation), ] Wrong continued indentation (add 10 spaces).
                                verbose_field_name)
                                ^         |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:118: [C0330(bad-continuation), ] Wrong continued indentation (add 28 spaces).
                            ' (%s.%s)' % (field.rel.to._meta.object_name, field.rel.field_name) if field.rel else ''))
                            ^                           |
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:15: [W0622(redefined-builtin), ] Redefining built-in 'input'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:15: [E0401(import-error), ] Unable to import 'django.utils.six.moves'
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:52: [R0914(too-many-locals), Command.handle] Too many local variables (16/15)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:52: [R0912(too-many-branches), Command.handle] Too many branches (23/12)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:52: [R0915(too-many-statements), Command.handle] Too many statements (65/50)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py:49: [W0201(attribute-defined-outside-init), Command.execute] Attribute 'stdin' defined outside __init__
************* Module django.contrib.auth.tests.custom_user
/usr/local/lib/python2.7/site-packages/django/contrib/auth/tests/custom_user.py:87: [W0201(attribute-defined-outside-init), RemoveGroupsAndPermissions.__enter__] Attribute '_old_au_local_m2m' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/auth/tests/custom_user.py:88: [W0201(attribute-defined-outside-init), RemoveGroupsAndPermissions.__enter__] Attribute '_old_pm_local_m2m' defined outside __init__
************* Module django.contrib.auth.migrations.0004_alter_user_username_opts
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0004_alter_user_username_opts.py:19: [C0301(line-too-long), ] Line too long (420/160)
************* Module django.contrib.auth.migrations.0001_initial
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0001_initial.py:56: [C0301(line-too-long), ] Line too long (196/160)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0001_initial.py:57: [C0301(line-too-long), ] Line too long (277/160)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0001_initial.py:61: [C0301(line-too-long), ] Line too long (165/160)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0001_initial.py:62: [C0301(line-too-long), ] Line too long (203/160)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0001_initial.py:64: [C0301(line-too-long), ] Line too long (266/160)
/usr/local/lib/python2.7/site-packages/django/contrib/auth/migrations/0001_initial.py:65: [C0301(line-too-long), ] Line too long (229/160)
************* Module django.contrib.contenttypes.fields
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:301: [C0330(bad-continuation), ] Wrong continued indentation (remove 1 space).
                    field.ct_field == self.content_type_field_name and
                   |^
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:302: [C0330(bad-continuation), ] Wrong continued indentation (remove 1 space).
                    field.fk_field == self.object_id_field_name
                   |^
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:303: [C0330(bad-continuation), ] Wrong continued indentation (remove 1 space).
                    for field in fields):
                   |^
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:310: [C0330(bad-continuation), ] Wrong hanging indentation (add 1 space).
                            target._meta.app_label, target._meta.object_name
                            ^|
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:311: [C0330(bad-continuation), ] Wrong hanging indentation.
                        ),
                        ^|   |
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:1: [C0302(too-many-lines), ] Too many lines in module (577/500)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:16: [R0902(too-many-instance-attributes), GenericForeignKey] Too many instance attributes (9/7)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:161: [W0622(redefined-builtin), GenericForeignKey.get_content_type] Redefining built-in 'id'
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:49: [W0201(attribute-defined-outside-init), GenericForeignKey.contribute_to_class] Attribute 'cache_attr' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:47: [W0201(attribute-defined-outside-init), GenericForeignKey.contribute_to_class] Attribute 'name' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:48: [W0201(attribute-defined-outside-init), GenericForeignKey.contribute_to_class] Attribute 'model' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:345: [W0201(attribute-defined-outside-init), GenericRelation.contribute_to_class] Attribute 'model' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py:442: [R0902(too-many-instance-attributes), create_generic_related_manager.GenericRelatedObjectManager] Too many instance attributes (11/7)
************* Module django.contrib.contenttypes.management
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:56: [C0325(superfluous-parens), ] Unnecessary parens after 'print' keyword
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:80: [C0325(superfluous-parens), ] Unnecessary parens after 'print' keyword
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:84: [C0325(superfluous-parens), ] Unnecessary parens after 'print' keyword
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:4: [W0622(redefined-builtin), ] Redefining built-in 'input'
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:4: [E0401(import-error), ] Unable to import 'django.utils.six.moves'
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:7: [R0914(too-many-locals), update_contenttypes] Too many local variables (16/15)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:50: [W0612(unused-variable), update_contenttypes] Unused variable 'model'
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py:7: [R0912(too-many-branches), update_contenttypes] Too many branches (13/12)
************* Module django.contrib.contenttypes.checks
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/checks.py:13: [C0330(bad-continuation), ] Wrong continued indentation (add 6 spaces).
        for cls in apps.get_models()
        ^     |
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/checks.py:14: [C0330(bad-continuation), ] Wrong continued indentation (add 6 spaces).
        for obj in six.itervalues(vars(cls))
        ^     |
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/checks.py:15: [C0330(bad-continuation), ] Wrong continued indentation (add 6 spaces).
        if isinstance(obj, GenericForeignKey))
        ^     |
************* Module django.contrib.contenttypes.forms
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:43: [C0330(bad-continuation), ] Wrong continued indentation (add 1 space).
            cls.ct_field.name, cls.ct_fk_field.name)
            ^|
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:48: [C0330(bad-continuation), ] Wrong continued indentation (add 4 spaces).
            ContentType.objects.get_for_model(self.instance).pk)
            ^   |
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:50: [C0330(bad-continuation), ] Wrong continued indentation (add 4 spaces).
            self.instance.pk)
            ^   |
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:20: [E1101(no-member), BaseGenericInlineFormSet.__init__] Instance of 'BaseGenericInlineFormSet' has no 'ct_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:20: [E1101(no-member), BaseGenericInlineFormSet.__init__] Instance of 'BaseGenericInlineFormSet' has no 'ct_fk_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:28: [E1101(no-member), BaseGenericInlineFormSet.__init__] Instance of 'BaseGenericInlineFormSet' has no 'ct_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:29: [E1101(no-member), BaseGenericInlineFormSet.__init__] Instance of 'BaseGenericInlineFormSet' has no 'for_concrete_model' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:30: [E1101(no-member), BaseGenericInlineFormSet.__init__] Instance of 'BaseGenericInlineFormSet' has no 'ct_fk_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:43: [E1101(no-member), BaseGenericInlineFormSet.get_default_prefix] Class 'BaseGenericInlineFormSet' has no 'ct_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:43: [E1101(no-member), BaseGenericInlineFormSet.get_default_prefix] Class 'BaseGenericInlineFormSet' has no 'ct_fk_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:47: [E1101(no-member), BaseGenericInlineFormSet.save_new] Instance of 'BaseGenericInlineFormSet' has no 'ct_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:49: [E1101(no-member), BaseGenericInlineFormSet.save_new] Instance of 'BaseGenericInlineFormSet' has no 'ct_fk_field' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:54: [R0913(too-many-arguments), generic_inlineformset_factory] Too many arguments (16/10)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:54: [R0914(too-many-locals), generic_inlineformset_factory] Too many local variables (18/15)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:76: [E1101(no-member), generic_inlineformset_factory] Instance of 'unicode' has no 'name' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:76: [E1101(no-member), generic_inlineformset_factory] Instance of 'unicode' has no 'name' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:78: [E1101(no-member), generic_inlineformset_factory] Instance of 'unicode' has no 'name' member
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/forms.py:78: [E1101(no-member), generic_inlineformset_factory] Instance of 'unicode' has no 'name' member
************* Module django.contrib.contenttypes.models
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:71: [W0612(unused-variable), ContentTypeManager.get_for_model] Unused variable 'created'
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:86: [W0621(redefined-outer-name), ContentTypeManager.get_for_models] Redefining name 'models' from outer scope (line 6)
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:128: [W0622(redefined-builtin), ContentTypeManager.get_for_id] Redefining built-in 'id'
************* Module django.contrib.contenttypes.generic
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:13: [C0413(wrong-import-position), ] Import "from django.contrib.contenttypes.admin import GenericInlineModelAdmin, GenericStackedInline, GenericTabularInline" should be placed at the top of the module
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:16: [C0413(wrong-import-position), ] Import "from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation" should be placed at the top of the module
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:19: [C0413(wrong-import-position), ] Import "from django.contrib.contenttypes.forms import BaseGenericInlineFormSet, generic_inlineformset_factory" should be placed at the top of the module
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:13: [W0611(unused-import), ] Unused GenericTabularInline imported from django.contrib.contenttypes.admin
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:13: [W0611(unused-import), ] Unused GenericStackedInline imported from django.contrib.contenttypes.admin
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:13: [W0611(unused-import), ] Unused GenericInlineModelAdmin imported from django.contrib.contenttypes.admin
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:16: [W0611(unused-import), ] Unused GenericForeignKey imported from django.contrib.contenttypes.fields
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:16: [W0611(unused-import), ] Unused GenericRelation imported from django.contrib.contenttypes.fields
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:19: [W0611(unused-import), ] Unused BaseGenericInlineFormSet imported from django.contrib.contenttypes.forms
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/generic.py:19: [W0611(unused-import), ] Unused generic_inlineformset_factory imported from django.contrib.contenttypes.forms
************* Module django.contrib.contenttypes.views
/usr/local/lib/python2.7/site-packages/django/contrib/contenttypes/views.py:11: [R0912(too-many-branches), shortcut] Too many branches (19/12)
************* Module django.contrib.sessions.middleware
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py:35: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                    domain=settings.SESSION_COOKIE_DOMAIN)
                    ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py:52: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                                request.session.session_key, max_age=max_age,
                                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py:53: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                                expires=expires, domain=settings.SESSION_COOKIE_DOMAIN,
                                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py:54: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                                path=settings.SESSION_COOKIE_PATH,
                                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py:55: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                                secure=settings.SESSION_COOKIE_SECURE or None,
                                ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py:56: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                                httponly=settings.SESSION_COOKIE_HTTPONLY or None)
                                ^           |
************* Module django.contrib.sessions.models
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/models.py:62: [C0413(wrong-import-position), ] Import "from django.contrib.sessions.backends.db import SessionStore" should be placed at the top of the module
************* Module django.contrib.sessions.backends.cache
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py:4: [W0622(redefined-builtin), ] Redefining built-in 'range'
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py:4: [E0401(import-error), ] Unable to import 'django.utils.six.moves'
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py:24: [W0703(broad-except), SessionStore.load] Catching too general exception Exception
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py:39: [W0612(unused-variable), SessionStore.create] Unused variable 'i'
************* Module django.contrib.sessions.backends.file
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/file.py:87: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                                e.__class__.__name__)
                                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/file.py:155: [C0330(bad-continuation), ] Wrong continued indentation (add 48 spaces).
                prefix=prefix + '_out_')
                ^                                               |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/file.py:151: [W0622(redefined-builtin), SessionStore.save] Redefining built-in 'dir'
************* Module django.contrib.sessions.backends.db
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py:27: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                        e.__class__.__name__)
                        ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py:86: [C0413(wrong-import-position), ] Import "from django.contrib.sessions.models import Session" should be placed at the top of the module
************* Module django.contrib.sessions.backends.base
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:107: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                        e.__class__.__name__)
                        ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:89: [W0622(redefined-builtin), SessionBase.encode] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:96: [W0622(redefined-builtin), SessionBase.decode] Redefining built-in 'hash'
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:102: [W0703(broad-except), SessionBase.decode] Catching too general exception Exception
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:140: [W0201(attribute-defined-outside-init), SessionBase.clear] Attribute '_session_cache' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:179: [W0201(attribute-defined-outside-init), SessionBase._get_session] Attribute '_session_cache' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:181: [W0201(attribute-defined-outside-init), SessionBase._get_session] Attribute '_session_cache' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py:286: [W0201(attribute-defined-outside-init), SessionBase.cycle_key] Attribute '_session_cache' defined outside __init__
************* Module django.contrib.sessions.backends.cached_db
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py:48: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                    self.get_expiry_age(expiry=s.expire_date))
                    ^           |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py:52: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                            e.__class__.__name__)
                            ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py:33: [W0703(broad-except), SessionStore.load] Catching too general exception Exception
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/cached_db.py:85: [C0413(wrong-import-position), ] Import "from django.contrib.sessions.models import Session" should be placed at the top of the module
************* Module django.contrib.sessions.backends.signed_cookies
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:16: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
                serializer=self.serializer,
                ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:17: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
                # This doesn't handle non-default expiry dates, see #19201
                ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:18: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
                max_age=settings.SESSION_COOKIE_AGE,
                ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:19: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
                salt='django.contrib.sessions.backends.signed_cookies')
                ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:75: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
            salt='django.contrib.sessions.backends.signed_cookies',
            ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:76: [C0330(bad-continuation), ] Wrong continued indentation (add 17 spaces).
            serializer=self.serializer)
            ^                |
/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/signed_cookies.py:55: [W0201(attribute-defined-outside-init), SessionStore.delete] Attribute '_session_cache' defined outside __init__
************* Module django.contrib.messages
/usr/local/lib/python2.7/site-packages/django/contrib/messages/__init__.py:1: [W0401(wildcard-import), ] Wildcard import django.contrib.messages.api
/usr/local/lib/python2.7/site-packages/django/contrib/messages/__init__.py:2: [W0401(wildcard-import), ] Wildcard import django.contrib.messages.constants
************* Module django.contrib.messages.api
/usr/local/lib/python2.7/site-packages/django/contrib/messages/api.py:28: [C0330(bad-continuation), ] Wrong continued indentation (add 9 spaces).
                    'django.contrib.messages.middleware.MessageMiddleware')
                    ^        |
************* Module django.contrib.messages.storage.cookie
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:86: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
                domain=settings.SESSION_COOKIE_DOMAIN,
                ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:87: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
                secure=settings.SESSION_COOKIE_SECURE or None,
                ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:88: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
                httponly=settings.SESSION_COOKIE_HTTPONLY or None)
                ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:91: [C0330(bad-continuation), ] Wrong continued indentation (add 19 spaces).
                domain=settings.SESSION_COOKIE_DOMAIN)
                ^                  |
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:17: [E0202(method-hidden), MessageEncoder.default] An attribute defined in json.encoder line 162 hides this method
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:76: [E1101(no-member), CookieStorage._get] Instance of 'Message' has no 'pop' member
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/cookie.py:154: [W0622(redefined-builtin), CookieStorage._decode] Redefining built-in 'hash'
************* Module django.contrib.messages.storage.base
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/base.py:92: [W0612(unused-variable), BaseStorage._loaded_messages] Unused variable 'all_retrieved'
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/base.py:170: [W0201(attribute-defined-outside-init), BaseStorage._get_level] Attribute '_level' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/base.py:183: [W0201(attribute-defined-outside-init), BaseStorage._set_level] Attribute '_level' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/messages/storage/base.py:93: [W0201(attribute-defined-outside-init), BaseStorage._loaded_messages] Attribute '_loaded_data' defined outside __init__
************* Module django.contrib.staticfiles.utils
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/utils.py:35: [W0622(redefined-builtin), get_files] Redefining built-in 'dir'
************* Module django.contrib.staticfiles.finders
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py:25: [W0622(redefined-builtin), BaseFinder.find] Redefining built-in 'all'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py:76: [W0622(redefined-builtin), FileSystemFinder.find] Redefining built-in 'all'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py:110: [W0612(unused-variable), FileSystemFinder.list] Unused variable 'prefix'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py:151: [W0622(redefined-builtin), AppDirectoriesFinder.find] Redefining built-in 'all'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py:199: [W0622(redefined-builtin), BaseStorageFinder.find] Redefining built-in 'all'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py:240: [W0622(redefined-builtin), find] Redefining built-in 'all'
************* Module django.contrib.staticfiles.storage
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py:20: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py:20: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.parse'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py:193: [R0914(too-many-locals), HashedFilesMixin.post_process] Too many local variables (23/15)
************* Module django.contrib.staticfiles.handlers
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py:5: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py:5: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.parse'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py:6: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py:6: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.request'
************* Module django.contrib.staticfiles.views
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py:12: [E0611(no-name-in-module), ] No name 'urllib' in module '_MovedItems'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/views.py:12: [E0401(import-error), ] Unable to import 'django.utils.six.moves.urllib.parse'
************* Module django.contrib.staticfiles.management.commands.runserver
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py:13: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help='Tells Django to NOT automatically serve static files at STATIC_URL.')
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py:15: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help='Allows serving static files even if DEBUG is False.')
            ^               |
************* Module django.contrib.staticfiles.management.commands.findstatic
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/findstatic.py:17: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            default=True,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/findstatic.py:18: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Only return the first match for each static file.")
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/findstatic.py:27: [C0330(bad-continuation), ] Wrong continued indentation (add 12 spaces).
                                  for location in finders.searched_locations))
                                  ^           |
************* Module django.contrib.staticfiles.management.commands.collectstatic
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:40: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            action='store_false', dest='interactive', default=True,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:41: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Do NOT prompt the user for input of any kind.")
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:43: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            action='store_false', dest='post_process', default=True,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:44: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Do NOT post process collected files.")
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:46: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            dest='ignore_patterns', metavar='PATTERN',
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:47: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Ignore files or directories matching this glob-style "
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:48: [C0330(bad-continuation), ] Wrong continued indentation.
                "pattern. Use multiple times to ignore more.")
                ^|          |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:50: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            action='store_true', dest='dry_run', default=False,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:51: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Do everything except modify the filesystem.")
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:53: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            action='store_true', dest='clear', default=False,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:54: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Clear the existing files using the storage "
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:57: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            action='store_true', dest='link', default=False,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:58: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Create a symbolic link to each file instead of copying.")
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:60: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            dest='use_default_ignore_patterns', default=True,
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:61: [C0330(bad-continuation), ] Wrong continued indentation (add 16 spaces).
            help="Don't ignore the common private glob-style patterns 'CVS', "
            ^               |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:62: [C0330(bad-continuation), ] Wrong continued indentation.
                "'.*' and '*~'.")
                ^|          |
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:12: [W0622(redefined-builtin), ] Redefining built-in 'input'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:12: [E0401(import-error), ] Unable to import 'django.utils.six.moves'
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:15: [R0902(too-many-instance-attributes), Command] Too many instance attributes (14/7)
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:79: [R0912(too-many-branches), Command.collect] Too many branches (14/12)
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:218: [R0101(too-many-nested-blocks), Command.delete_file] Too many nested blocks (6/5)
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:72: [W0201(attribute-defined-outside-init), Command.set_options] Attribute 'dry_run' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:69: [W0201(attribute-defined-outside-init), Command.set_options] Attribute 'verbosity' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:76: [W0201(attribute-defined-outside-init), Command.set_options] Attribute 'ignore_patterns' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:70: [W0201(attribute-defined-outside-init), Command.set_options] Attribute 'symlink' defined outside __init__
/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py:77: [W0201(